export { Hero } from './Hero'
export { About } from './About'
export { Features } from './Features'
export { HowItWorks } from './HowItWorks'
export { Benefits } from './Benefits'
export { ContactCTA } from './ContactCTA'
